spring:
 application:
    name: zuulgateway

eureka:
 instance:
    preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: false
  serviceUrl:
     defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    ORGANIZATIONSERVICE:
      url: http://localhost:8092/
    LICENSINGSERVICE:
      url: http://localhost:8091/